backend:
  name: git-gateway
  branch: main
  publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Home Page"
    # folder: "src/data"
    files: 
    - name: "hero.md"  # This should be the name of your file
      create: false
      label: "Hero"
      file: "src/data/home"
      fields:
        - { label: "Tagline", name: "tagline", widget: "string" }
        - { label: "Description", name: "description", widget: "string" }
        - { label: "Button URL", name: "btnUrl", widget: "string" }
        - { label: "Button Text", name: "btnText", widget: "string" }
        - { label: "Featured Photo", name: "Headshot", widget: "image" }

    - name: "event.md"  # This should be the name of your file
      create: false
      label: "Event"
      file: "src/data/home"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Description", name: "desc", widget: "string" }
        - { label: "Button Text", name: "btnText", widget: "string" }
        - { label: "Featured Photo", name: "img", widget: "image" }

    - name: "story.md"
      label: "Story"
      file: "src/data/home"
      create: false
      # slug: "story.md"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Super Title", name: "supTitle", widget: "string" }

  - label: "Story Cards"
    name: "storyCards"
    folder: "src/data/home/story"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Featured Image", name: "imgUrl", widget: "image" }
      - { label: "Poster Title", name: "posterTitle", widget: "string" }
      - { label: "Poster Description", name: "posterDesc", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "about"
    label: "About Us"
    folder: "src/data"
    create: false
    slug: "about.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Background Color", name: "bgColor", widget: "string" }
      - { label: "Background Image", name: "bgImg", widget: "image" }

  - name: "church"
    label: "Church"
    folder: "src/data"
    create: false
    slug: "church.md"
    fields:
      - { label: "Image URL", name: "imgUrl", widget: "string" }
      - { label: "Playlist Id", name: "playlistId", widget: "string" }

  - name: "events" # Used in routes, e.g., /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "src/data/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}

  
